### ISSUE TITLE
SSL Certificate Issue?

### ISSUE THREAD

**Issue by stuchalk** [lmhale99/pycdcs#2]
If I run the following, I get the SSL error below where I did not get it before.  Any ideas how to fix? (i'm using v0.1.8)

```
import cdcs
from cdcs import CDCS

# requires NIST VPN login
print('Notebook version', cdcs.__version__)
curator = CDCS('https://xxxambench2022.nist.gov/', username='sjc4', password='****')
print(curator.template_titles)
exit()

```

`
requests.exceptions.SSLError: HTTPSConnectionPool(host='xxxambench2022.nist.gov', port=443): Max retries exceeded with url: /rest/data/?title=ARBITRARYNONEXISTANTTITLE (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
`

NOTE: 'xxxambench2022.nist.gov'  is a fake URL for security reasons...

**Comment by lmhale99** [comment]
@stuchalk,

I think maybe the VPN access requires specifying a certificate? I'm asking the CDCS development people about this to see what to do.

**Comment by stuchalk** [comment]
I pinged Kevin Brady at NIST about this but he was able to access it no problem.  So, I thought it might be something in the cdcs code as I had it working at one point and the only change was the update to 0.1.8.  Anyway, anything you can find out about a required CERT would be great.

**Comment by lmhale99** [comment]
He just sent me a snippet of his own code.  Try adding verify=False to the CDCS initialization.

**Comment by stuchalk** [comment]
Sadly, using 
`curator = CDCS('https://xxxambench2022.nist.gov/', username='sjc4', password='****', verify=False)
`
does not fix the issue...

**Comment by lmhale99** [comment]
It's working for me with the potentials site and I'm consistent with the 0.1.8 release.  

An anonymous link (username='') also worked for me on the am site.  Try that out and let me know.  

I'm trying to login to the am site myself. Apparently I have an account and don't know the password and the reset is slow or broken.

**Comment by stuchalk** [comment]
Still not working.  Can you tell me Python packages you are using and their versions?  It would be good to have a requirements.txt file in the repo.  Its got to be a config issue on my end or the missing cert...  If you find the cert could you email it to me?

**Comment by lmhale99** [comment]
I just did a fresh conda environment and only called 
    
    conda install cdcs -c conda-forge  

cdcs only has requests and pandas as direct requirements, so everything else came from those two.  These are the packages and versions I got for Python 3.10 and 3.7:

| Name | Version (3.10) | Version (3.7) |
| ------ | -------- | --------- |
| _libgcc_mutex | 0.1    | 0.1 |
| _openmp_mutex | 4.5   | 4.5 |
| blas |  | 1.0 |
| bottleneck |  | 1.3.4 |
| brotlipy | 0.7.0      | 0.7.0 |
| bzip2 | 1.0.8       |  |
| ca-certificates | 2021.10.8    | 2021.10.8    | 
| cdcs | 0.1.8          | 0.1.8          | 
| certifi | 2021.10.8  |    2021.10.8  |    
| cffi | 1.15.0       |  1.15.0       |  
| charset-normalizer | 2.0.12 |  2.0.12 | 
| cryptography | 36.0.2 |  35.0.0 |
| idna | 3.3  | 3.3  | 
| intel-openmp | | 2021.4.0 |
| ld_impl_linux-64 | 2.36.1   |  2.35.1   | 
| libblas | 3.9.0 |  |
| libcblas | 3.9.0 |  |
| libffi | 3.4.2 |  3.3 |
| libgcc-ng | 11.2.0 | 9.3.0 |
| libgfortran-ng | 11.2.0 | |
| libgfortran5 | 11.2.0 | |
| libgomp | 11.2.0 | 9.3.0 |
| liblapack | 3.9.0 | |
| libnsl | 2.0.0 | |
| libopenblas | 0.3.20 | |
| libstdcxx-ng | 11.2.0 | 9.3.0 |
| libuuid | 2.32.1 | |
| libzlib | 1.2.11 | |
| mkl | | 2021.4.0 |
| mkl-service | | 2.4.0 |
| mkl_fft | | 1.3.1 |
| mkl_random | | 1.2.2 |
| ncurses | 6.3   |  6.3   | 
| numpy | 1.22.3  | 1.21.5 |
| openssl | 1.1.1o | 1.1.1n |
| packaging | | 21.3 |
| pandas | 1.4.2 | 1.3.4 |
| pip | 22.0.4  |  21.2.2 |
| pycparser | 2.21  |  2.21  |  
| pyopenssl | 22.0.0  |  22.0.0  | 
| pysocks | 1.7.1   |   1.7.1   | 
| python | 3.10.4   |  3.7.13 |
| python-dateutil | 2.8.2   |  2.8.2   | 
| python_abi | 3.10    |  3.7 |
| pytz | 2022.1  |  2022.1  | 
| readline | 8.1 |  8.1.2 |
| requests | 2.27.1      |   2.27.1      | 
| setuptools | 62.1.0  |  61.2.0  | 
| six | 1.16.0 |  1.16.0 | 
| sqlite | 3.38.3  |   3.38.2  | 
| tk | 8.6.12 |  8.6.11 | 
| tzdata | 2022a | |
| urllib3 | 1.26.9 |   1.26.9 | 
| wheel | 0.37.1 |   0.37.1 | 
| xz  | 5.2.5 | 5.2.5 | 
| zlib | 1.2.11 |  1.2.12 |

**Comment by lmhale99** [comment]
Maybe check the version of requests, ca-certificates and certifi packages?

I just tried the test-am site and I can login from Python using verify=False.  You can try that site. Or try anonymous login to the potentials site.

**Comment by stuchalk** [comment]
OK, I was able to get it working with verify=False by adding pyopenssl (I use PiPy only not conda).  Sorry this took so long to diagnose.  I can do a pull request to add a requirements.txt file so others don't have the same issue...or I could becoming a collaborator on the project if that were of interest.

**Comment by lmhale99** [comment]
If you want, I can add you as a collaborator.  That way you can possibly set up some CI stuff as well?

I'm not sure if it was an issue with package versions, operating system, or simply some machines need the extra pyopenssl.

I tried a new fresh environment and used pip install and pip freeze and saw only these:
cdcs==0.1.8
certifi==2021.10.8
charset-normalizer==2.0.12
idna==3.3
numpy==1.21.6
pandas==1.3.5
python-dateutil==2.8.2
pytz==2022.1
requests==2.27.1
six==1.16.0
urllib3==1.26.9

**Comment by stuchalk** [comment]
So, I did the same thing and came up with this as the set of packages that get installed by adding cdcs and requests.  Interestingly, it worked without having pyopenssl this time :(   Not sure why...

![Screen Shot 2022-05-04 at 2 19 40 PM](https://user-images.githubusercontent.com/540150/166801021-33b4220e-9134-4dd1-9397-ac3e4c72e5e5.jpg)

So in the end, the alignment of installed packages is not that different...

**Comment by stuchalk** [comment]
Lucas

Is there a way in the CDCS software to retrieve documents created after a certain date?
Maybe via the mongoquery option?

Stuart

On May 4, 2022, at 12:46 PM, Lucas Hale ***@***.******@***.***>> wrote:



If you want, I can add you as a collaborator. That way you can possibly set up some CI stuff as well?

I'm not sure if it was an issue with package versions, operating system, or simply some machines need the extra pyopenssl.

I tried a new fresh environment and used pip install and pip freeze and saw only these:
cdcs==0.1.8
certifi==2021.10.8
charset-normalizer==2.0.12
idna==3.3
numpy==1.21.6
pandas==1.3.5
python-dateutil==2.8.2
pytz==2022.1
requests==2.27.1
six==1.16.0
urllib3==1.26.9

**Comment by lmhale99** [comment]
Hi @stuchalk, 

Kind of, in a few different non-equal ways?

1. When you get records with query, there are creation_date, last_modification_date, and last_change_date fields for each record. You can parse these after querying by transforming the iso strings into datetime objects and comparing with a reference datetime. I think I'll patch the query and get methods to do this automatically parse these fields as I don't see any major negatives in doing so. 

```python
records = curator.query(template)
def parse_date(series, key):
    return datetime.datetime.fromisoformat(series[key].strip('Z'))
for key in ['creation_date', 'last_modification_date', 'last_change_date']:
    records[key] = records.apply(parse_date, args=[key], axis=1)
```

2. If you want to parse during the query, I think the only way to do so currently is to add a datetime field inside your record contents and then the mongoquery option should allow date comparisons: https://www.thecodebuzz.com/mongodb-date-range-query-greater-than-less-than/. The main downside here is modifying all your records to have this field in them.

3.  You would think then that 1+2 could be combined in some way, but the current design of the CDCS REST API calls do not allow it. The mongo queries in CDCS start at the "content" level, meaning they only operate on the xml records themselves and not the associated metadata. Right now, they would have to add functionality to the REST calls so that web submitted parameters or data can then be compared to the metadata date fields. I can ask them about this, but I'm not sure how easy or straightforward implementing this would be.

**Comment by stuchalk** [comment]
OK, I will try this out.  Thanks!

**Comment by lmhale99** [comment]
I just pushed automatic date field parsing to this repository.  It changes the date fields for records and blobs into pandas.Timestamp objects. pandas was automatically transforming datetime values to Timestamps so I just went with them.  Interpreting can be turned off by setting parse_dates=False.

Comparing Timestamps is a bit finicky in that it makes you specify a time zone since the ones from CDCS have that info. For example: 
`ref_date = pd.Timestamp(year=2022, month=10, day=5, tz='UTC')`
